name: github pages

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master, checkin ]

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: Build
        run: |
          cd CHECKIN
          bash .build-pages.sh

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./CHECKIN/public
          enable_jekyll: true
